"""Add OTP tables

Revision ID: 999999999999
Revises: 3375db3f15dc
Create Date: 2025-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '999999999999'
down_revision = '3375db3f15dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create registration_requests table
    op.create_table('registration_requests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=80), nullable=False),
        sa.Column('email', sa.String(length=120), nullable=False),
        sa.Column('full_name', sa.String(length=200), nullable=True),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('otp_code', sa.String(length=6), nullable=False),
        sa.Column('otp_expires_at', sa.DateTime(), nullable=False),
        sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
        sa.Column('admin_notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('approved_at', sa.DateTime(), nullable=True),
        sa.Column('approved_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_registration_requests_otp_expires_at', 'registration_requests', ['otp_expires_at'], unique=False)
    op.create_index('idx_registration_requests_status', 'registration_requests', ['status'], unique=False)
    op.create_index('idx_registration_requests_created_at', 'registration_requests', ['created_at'], unique=False)
    
    # Create admin_notifications table
    op.create_table('admin_notifications',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('registration_request_id', sa.Integer(), nullable=False),
        sa.Column('admin_id', sa.Integer(), nullable=True),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('notification_type', sa.String(length=50), server_default='registration_request', nullable=False),
        sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('is_sent', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('email_sent_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('read_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['registration_request_id'], ['registration_requests.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create otp_email_logs table
    op.create_table('otp_email_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('registration_request_id', sa.Integer(), nullable=False),
        sa.Column('recipient_email', sa.String(length=120), nullable=False),
        sa.Column('subject', sa.String(length=200), nullable=False),
        sa.Column('email_type', sa.String(length=50), nullable=False),
        sa.Column('is_sent', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('sent_at', sa.DateTime(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['registration_request_id'], ['registration_requests.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('otp_email_logs')
    op.drop_table('admin_notifications')
    op.drop_table('registration_requests')
    # ### end Alembic commands ###