"""add_classified_at_and_sync_schema

Revision ID: c089d130b448
Revises: ddc188783081
Create Date: 2025-12-10 20:23:03.190335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c089d130b448'
down_revision = 'ddc188783081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop tables in correct order (metrics depends on runs)
    op.drop_table('training_metrics')
    op.drop_table('training_runs')
    op.drop_table('classification_configs')
    
    with op.batch_alter_table('admin_notifications', schema=None) as batch_op:
        batch_op.alter_column('notification_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'registration_request'::character varying"))
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('is_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_admin_notifications_admin_id'))
        batch_op.drop_index(batch_op.f('idx_admin_notifications_is_read'))
        batch_op.drop_index(batch_op.f('idx_admin_notifications_is_sent'))
        batch_op.drop_index(batch_op.f('idx_admin_notifications_registration_request_id'))

    with op.batch_alter_table('classification_results', schema=None) as batch_op:
        batch_op.alter_column('model_name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_classification_results_classified_at'))
        batch_op.drop_index(batch_op.f('idx_classification_results_classified_by'))
        batch_op.drop_index(batch_op.f('idx_classification_results_data_id'))
        batch_op.drop_index(batch_op.f('idx_classification_results_data_type'))
        batch_op.drop_index(batch_op.f('idx_classification_results_data_type_id'))
        batch_op.drop_index(batch_op.f('idx_classification_results_model_name'))
        batch_op.drop_index(batch_op.f('idx_classification_results_prediction'))

    with op.batch_alter_table('clean_data_scraper', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_clean_data_scraper_cleaned_by'))
        batch_op.drop_index(batch_op.f('idx_clean_data_scraper_content_fts'), postgresql_using='gin')
        batch_op.drop_index(batch_op.f('idx_clean_data_scraper_created_at'))
        batch_op.drop_index(batch_op.f('idx_clean_data_scraper_dataset_id'))
        batch_op.drop_index(batch_op.f('idx_clean_data_scraper_platform'))
        batch_op.drop_index(batch_op.f('idx_clean_data_scraper_raw_data_scraper_id'))
        batch_op.drop_constraint(batch_op.f('clean_data_scraper_raw_data_scraper_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('clean_data_scraper_cleaned_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'raw_data_scraper', ['raw_data_scraper_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['cleaned_by'], ['id'])

    with op.batch_alter_table('clean_data_upload', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_clean_data_upload_cleaned_by'))
        batch_op.drop_index(batch_op.f('idx_clean_data_upload_content_fts'), postgresql_using='gin')
        batch_op.drop_index(batch_op.f('idx_clean_data_upload_created_at'))
        batch_op.drop_index(batch_op.f('idx_clean_data_upload_dataset_id'))
        batch_op.drop_index(batch_op.f('idx_clean_data_upload_platform'))
        batch_op.drop_index(batch_op.f('idx_clean_data_upload_raw_data_id'))
        batch_op.drop_constraint(batch_op.f('clean_data_upload_raw_data_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('clean_data_upload_cleaned_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['cleaned_by'], ['id'])
        batch_op.create_foreign_key(None, 'raw_data', ['raw_data_id'], ['id'])

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_datasets_name'))
        batch_op.drop_index(batch_op.f('idx_datasets_uploaded_by'))

    with op.batch_alter_table('otp_email_logs', schema=None) as batch_op:
        batch_op.alter_column('is_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_otp_email_logs_created_at'))
        batch_op.drop_index(batch_op.f('idx_otp_email_logs_email_type'))
        batch_op.drop_index(batch_op.f('idx_otp_email_logs_is_sent'))
        batch_op.drop_index(batch_op.f('idx_otp_email_logs_registration_request_id'))
        batch_op.drop_index(batch_op.f('idx_otp_email_logs_user_id'))

    with op.batch_alter_table('raw_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_raw_data_created_at'))
        batch_op.drop_index(batch_op.f('idx_raw_data_platform'))
        batch_op.drop_index(batch_op.f('idx_raw_data_status'))
        batch_op.drop_index(batch_op.f('idx_raw_data_uploaded_by'))
        batch_op.drop_constraint(batch_op.f('raw_data_uploaded_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['uploaded_by'], ['id'])

    with op.batch_alter_table('raw_data_scraper', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_raw_data_scraper_created_at'))
        batch_op.drop_index(batch_op.f('idx_raw_data_scraper_platform'))
        batch_op.drop_index(batch_op.f('idx_raw_data_scraper_scraped_by'))
        batch_op.drop_index(batch_op.f('idx_raw_data_scraper_status'))
        batch_op.drop_constraint(batch_op.f('raw_data_scraper_scraped_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['scraped_by'], ['id'])

    with op.batch_alter_table('registration_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_registration_requests_created_at'))
        batch_op.drop_index(batch_op.f('idx_registration_requests_otp_expires_at'))
        batch_op.drop_index(batch_op.f('idx_registration_requests_status'))
        batch_op.create_index(batch_op.f('ix_registration_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_requests_otp_expires_at'), ['otp_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_requests_status'), ['status'], unique=False)

    with op.batch_alter_table('user_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_activities_created_at'))
        batch_op.drop_index(batch_op.f('idx_user_activities_user_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
        batch_op.drop_index(batch_op.f('idx_users_created_at'))
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_index(batch_op.f('idx_users_is_active'))
        batch_op.drop_index(batch_op.f('idx_users_role'))
        batch_op.drop_index(batch_op.f('idx_users_username'))
        batch_op.drop_column('email_notifications')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('language_preference')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('timezone')
        batch_op.drop_column('theme_preference')
        batch_op.drop_column('classified_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classified_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('theme_preference', sa.VARCHAR(length=20), server_default=sa.text("'dark'::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.VARCHAR(length=50), server_default=sa.text("'Asia/Jakarta'::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('language_preference', sa.VARCHAR(length=10), server_default=sa.text("'id'::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email_notifications', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('idx_users_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'user'::character varying"))

    with op.batch_alter_table('user_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_activities_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_activities_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('registration_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registration_requests_status'))
        batch_op.drop_index(batch_op.f('ix_registration_requests_otp_expires_at'))
        batch_op.drop_index(batch_op.f('ix_registration_requests_created_at'))
        batch_op.create_index(batch_op.f('idx_registration_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_registration_requests_otp_expires_at'), ['otp_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_registration_requests_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))

    with op.batch_alter_table('raw_data_scraper', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('raw_data_scraper_scraped_by_fkey'), 'users', ['scraped_by'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_raw_data_scraper_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_raw_data_scraper_scraped_by'), ['scraped_by'], unique=False)
        batch_op.create_index(batch_op.f('idx_raw_data_scraper_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('idx_raw_data_scraper_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('raw_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('raw_data_uploaded_by_fkey'), 'users', ['uploaded_by'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_raw_data_uploaded_by'), ['uploaded_by'], unique=False)
        batch_op.create_index(batch_op.f('idx_raw_data_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_raw_data_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('idx_raw_data_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('otp_email_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_otp_email_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_otp_email_logs_registration_request_id'), ['registration_request_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_otp_email_logs_is_sent'), ['is_sent'], unique=False)
        batch_op.create_index(batch_op.f('idx_otp_email_logs_email_type'), ['email_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_otp_email_logs_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('is_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_datasets_uploaded_by'), ['uploaded_by'], unique=False)
        batch_op.create_index(batch_op.f('idx_datasets_name'), ['name'], unique=False)

    with op.batch_alter_table('clean_data_upload', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('clean_data_upload_cleaned_by_fkey'), 'users', ['cleaned_by'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('clean_data_upload_raw_data_id_fkey'), 'raw_data', ['raw_data_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_clean_data_upload_raw_data_id'), ['raw_data_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_clean_data_upload_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('idx_clean_data_upload_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_clean_data_upload_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_clean_data_upload_content_fts'), [sa.literal_column("to_tsvector('indonesian'::regconfig, content)")], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('idx_clean_data_upload_cleaned_by'), ['cleaned_by'], unique=False)

    with op.batch_alter_table('clean_data_scraper', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('clean_data_scraper_cleaned_by_fkey'), 'users', ['cleaned_by'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('clean_data_scraper_raw_data_scraper_id_fkey'), 'raw_data_scraper', ['raw_data_scraper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_clean_data_scraper_raw_data_scraper_id'), ['raw_data_scraper_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_clean_data_scraper_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('idx_clean_data_scraper_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_clean_data_scraper_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_clean_data_scraper_content_fts'), [sa.literal_column("to_tsvector('indonesian'::regconfig, content)")], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('idx_clean_data_scraper_cleaned_by'), ['cleaned_by'], unique=False)

    with op.batch_alter_table('classification_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_classification_results_prediction'), ['prediction'], unique=False)
        batch_op.create_index(batch_op.f('idx_classification_results_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('idx_classification_results_data_type_id'), ['data_type', 'data_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_classification_results_data_type'), ['data_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_classification_results_data_id'), ['data_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_classification_results_classified_by'), ['classified_by'], unique=False)
        batch_op.create_index(batch_op.f('idx_classification_results_classified_at'), ['classified_at'], unique=False)
        batch_op.alter_column('model_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('admin_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_admin_notifications_registration_request_id'), ['registration_request_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_admin_notifications_is_sent'), ['is_sent'], unique=False)
        batch_op.create_index(batch_op.f('idx_admin_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('idx_admin_notifications_admin_id'), ['admin_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('is_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('notification_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'registration_request'::character varying"))

    op.create_table('classification_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('visible_algorithms', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('classification_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('classification_configs_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('classification_configs_pkey'))
    )
    op.create_table('training_runs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('training_runs_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('row_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('col_text', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('col_label', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_applied', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('word2vec_model_path', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='training_runs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='training_runs_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('training_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_training_runs_is_applied'), ['is_applied'], unique=False)
        batch_op.create_index(batch_op.f('idx_training_runs_finished_at'), ['finished_at'], unique=False)

    op.create_table('training_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('precision', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('recall', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('f1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('confusion_matrix', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['training_runs.id'], name=op.f('training_metrics_run_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('training_metrics_pkey'))
    )
    with op.batch_alter_table('training_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_training_metrics_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_training_metrics_model_name'), ['model_name'], unique=False)

    # ### end Alembic commands ###
