"""Add profile_picture to users table

Revision ID: d02f3e9c2890
Revises: c089d130b448
Create Date: 2025-12-18 06:55:10.862497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd02f3e9c2890'
down_revision = 'c089d130b448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('users')]

    if 'profile_picture' not in columns:
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('users')]

    if 'profile_picture' in columns:
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.drop_column('profile_picture')
    # ### end Alembic commands ###
